[package]
name = "credshim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "credshim"
path = "src/main.rs"

[features]
testing = ["credshim-mitm/testing"]

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
credshim-aws.workspace = true
credshim-core.workspace = true
credshim-mitm.workspace = true
credshim-oauth.workspace = true
credshim-secrets.workspace = true
credshim-ssh.workspace = true
rpassword = "7"
rustix.workspace = true
rustls.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
time = { workspace = true, features = ["formatting"] }
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
credshim-secrets.workspace = true
secrecy.workspace = true
credshim-testkit.workspace = true
serde_json.workspace = true
tokio.workspace = true
