[package]
name = "credshim-aws"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aws-credential-types.workspace = true
aws-sigv4.workspace = true
bytes.workspace = true
credshim-core.workspace = true
credshim-secrets.workspace = true
form_urlencoded = "1"
hex.workspace = true
http.workspace = true
percent-encoding.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time", "rt"] }
tracing.workspace = true
time = { workspace = true, features = ["macros", "parsing"] }
zeroize.workspace = true

[dev-dependencies]
tokio.workspace = true
time = { workspace = true, features = ["macros", "parsing"] }
credshim-testkit.workspace = true
toml.workspace = true

[lints]
workspace = true
