import json
import pathlib
import sys

CREDENTIAL_MEMBERS = {"secretaccesskey", "sessiontoken"}


def returns_credentials(shapes, name, seen):
    if name in seen:
        return False
    seen.add(name)
    shape = shapes[name]
    kind = shape["type"]
    if kind == "structure":
        return any(
            member.lower() in CREDENTIAL_MEMBERS or returns_credentials(shapes, spec["shape"], seen)
            for member, spec in shape.get("members", {}).items()
        )
    if kind == "list":
        return returns_credentials(shapes, shape["member"]["shape"], seen)
    if kind == "map":
        return returns_credentials(shapes, shape["value"]["shape"], seen)
    return False


def main(data, version, endpoints_out):
    endpoints = set()
    rows = []
    for model in sorted(pathlib.Path(data).glob("*/*/service-2.json")):
        service = json.loads(model.read_text())
        meta = service["metadata"]
        endpoints.add((meta.get("signingName", meta["endpointPrefix"]).lower(), meta["endpointPrefix"]))
        shapes = service["shapes"]
        for op_name, op in service["operations"].items():
            output = op.get("output", {}).get("shape")
            if not output or not returns_credentials(shapes, output, set()):
                continue
            http = op.get("http", {})
            rows.append(
                (
                    meta.get("signingName", meta["endpointPrefix"]),
                    meta["endpointPrefix"],
                    op_name,
                    http.get("method", "POST"),
                    http.get("requestUri", "/"),
                    "noAuth" if op.get("authtype") == "none" or op.get("auth") == ["smithy.api#noAuth"] else "sigv4",
                )
            )
    print("// @generated by scripts/aws/credential-operations.py from the botocore models in " + version)
    print("")
    print("use crate::operation::{Auth, CredentialOperation};")
    print("")
    print("pub(crate) const CREDENTIAL_OPERATIONS: &[CredentialOperation] = &[")
    for signing_name, prefix, op, method, uri, auth in sorted(set(rows)):
        print("    CredentialOperation {")
        print(f"        signing_name: {json.dumps(signing_name)},")
        print(f"        endpoint_prefix: {json.dumps(prefix)},")
        print(f"        name: {json.dumps(op)},")
        print(f"        method: {json.dumps(method)},")
        print(f"        request_uri: {json.dumps(uri)},")
        print(f"        auth: Auth::{'None' if auth == 'noAuth' else 'SigV4'},")
        print("    },")
    print("];")
    with open(endpoints_out, "w") as out:
        out.write("// @generated by scripts/aws/credential-operations.py from the botocore models in " + version + "\n\n")
        out.write("pub(crate) const SERVICE_ENDPOINTS: &[(&str, &str)] = &[\n")
        for signing_name, prefix in sorted(endpoints):
            out.write(f"    ({json.dumps(signing_name)}, {json.dumps(prefix)}),\n")
        out.write("];\n")


main(sys.argv[1], sys.argv[2], sys.argv[3])
