import json
import pathlib
import sys

CREDENTIAL_MEMBERS = {"secretaccesskey", "sessiontoken"}


def returns_credentials(shapes, name, seen):
    if name in seen:
        return False
    seen.add(name)
    shape = shapes[name]
    kind = shape["type"]
    if kind == "structure":
        return any(
            member.lower() in CREDENTIAL_MEMBERS or returns_credentials(shapes, spec["shape"], seen)
            for member, spec in shape.get("members", {}).items()
        )
    if kind == "list":
        return returns_credentials(shapes, shape["member"]["shape"], seen)
    if kind == "map":
        return returns_credentials(shapes, shape["value"]["shape"], seen)
    return False


def required_members(shapes, op, location):
    shape_name = op.get("input", {}).get("shape")
    if not shape_name:
        return []
    shape = shapes[shape_name]
    return sorted(
        shape["members"][member].get("locationName", member)
        for member in shape.get("required", [])
        if shape["members"][member].get("location") == location
    )


def rest_operation(meta, shapes, op_name, op):
    http = op["http"]
    path, _, literal = http["requestUri"].partition("?")
    query = [part for part in literal.split("&") if part]
    query += [key for key in required_members(shapes, op, "querystring") if key not in query]
    return (
        meta.get("signingName", meta["endpointPrefix"]).lower(),
        meta["endpointPrefix"],
        op_name,
        http["method"],
        path,
        tuple(sorted(query)),
        tuple(key.lower() for key in required_members(shapes, op, "header")),
    )


def write_rest_operations(out_path, version, rows):
    with open(out_path, "w") as out:
        out.write("// @generated by scripts/aws/credential-operations.py from the botocore models in " + version + "\n\n")
        out.write("use crate::operation::RestOperation;\n\n")
        out.write("pub(crate) const REST_OPERATIONS: &[RestOperation] = &[\n")
        for signing_name, prefix, op, method, path, query, headers in sorted(set(rows)):
            fields = [
                f"signing_name: {json.dumps(signing_name)}",
                f"endpoint_prefix: {json.dumps(prefix)}",
                f"name: {json.dumps(op)}",
                f"method: {json.dumps(method)}",
                f"path: {json.dumps(path)}",
                "query: &[" + ", ".join(json.dumps(q) for q in query) + "]",
                "headers: &[" + ", ".join(json.dumps(h) for h in headers) + "]",
            ]
            out.write("    RestOperation { " + ", ".join(fields) + " },\n")
        out.write("];\n")


def main(data, version, endpoints_out, rest_out):
    endpoints = set()
    rows = []
    rest_rows = []
    for model in sorted(pathlib.Path(data).glob("*/*/service-2.json")):
        service = json.loads(model.read_text())
        meta = service["metadata"]
        endpoints.add((meta.get("signingName", meta["endpointPrefix"]).lower(), meta["endpointPrefix"]))
        shapes = service["shapes"]
        for op_name, op in service["operations"].items():
            if meta["protocol"] in ("rest-json", "rest-xml"):
                rest_rows.append(rest_operation(meta, shapes, op_name, op))
            output = op.get("output", {}).get("shape")
            if not output or not returns_credentials(shapes, output, set()):
                continue
            http = op.get("http", {})
            rows.append(
                (
                    meta.get("signingName", meta["endpointPrefix"]),
                    meta["endpointPrefix"],
                    op_name,
                    http.get("method", "POST"),
                    http.get("requestUri", "/"),
                    "noAuth" if op.get("authtype") == "none" or op.get("auth") == ["smithy.api#noAuth"] else "sigv4",
                )
            )
    print("// @generated by scripts/aws/credential-operations.py from the botocore models in " + version)
    print("")
    print("use crate::operation::{Auth, CredentialOperation};")
    print("")
    print("pub(crate) const CREDENTIAL_OPERATIONS: &[CredentialOperation] = &[")
    for signing_name, prefix, op, method, uri, auth in sorted(set(rows)):
        print("    CredentialOperation {")
        print(f"        signing_name: {json.dumps(signing_name)},")
        print(f"        endpoint_prefix: {json.dumps(prefix)},")
        print(f"        name: {json.dumps(op)},")
        print(f"        method: {json.dumps(method)},")
        print(f"        request_uri: {json.dumps(uri)},")
        print(f"        auth: Auth::{'None' if auth == 'noAuth' else 'SigV4'},")
        print("    },")
    print("];")
    with open(endpoints_out, "w") as out:
        out.write("// @generated by scripts/aws/credential-operations.py from the botocore models in " + version + "\n\n")
        out.write("pub(crate) const SERVICE_ENDPOINTS: &[(&str, &str)] = &[\n")
        for signing_name, prefix in sorted(endpoints):
            out.write(f"    ({json.dumps(signing_name)}, {json.dumps(prefix)}),\n")
        out.write("];\n")
    write_rest_operations(rest_out, version, rest_rows)


main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
