[package]
name = "credshim-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aho-corasick.workspace = true
base64.workspace = true
bytes.workspace = true
form_urlencoded = "1"
getrandom.workspace = true
http.workspace = true
percent-encoding.workspace = true
secrecy.workspace = true
serde.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
base64.workspace = true
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
